version: '3'

services:
  custom-wordpress:
    build: ./wordpress-eigenes-image
    ports:
      - "8080:80"
    environment:
      WORDPRESS_DB_HOST: custom-mysql
      WORDPRESS_DB_USER: user
      WORDPRESS_DB_PASSWORD: password
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - ./wp-content:/var/www/html/wp-content
    networks:
      - mynetwork

  custom-mysql:
    build: ./mysql-eigenes-image
    environment:
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: wordpress
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - ./mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
